apiVersion: v1
kind: Service
metadata:
  namespace: stg
  name: web
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http