apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stg
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: destiny1616/nginx:v3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: rails-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql 
        - name: empty-dir
          mountPath: /analytics_app/tmp/sockets
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          timeoutSeconds: 30
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          timeoutSeconds: 30
          initialDelaySeconds: 30
          periodSeconds: 30
      - name: rails
        image: destiny1616/rails:v15
        imagePullPolicy: Always
        command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
        envFrom:
        - configMapRef:
            name: rails-config
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql 
        - name: empty-dir
          mountPath: /analytics_app/tmp/sockets
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          timeoutSeconds: 30
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          timeoutSeconds: 30
          initialDelaySeconds: 30
          periodSeconds: 30            
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: empty-dir
        emptyDir: {}                  