apiVersion: v1
kind: Service
metadata:
  namespace: stg
  name: web
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stg
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: destiny1616/nginx:v3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: rails-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql 
        - name: empty-dir
          mountPath: /analytics_app/tmp/sockets
      - name: rails
        image: destiny1616/rails:v6
        imagePullPolicy: Always
        command: ["foreman", "start", "-f", "Procfile.dev"]
        envFrom:
        - configMapRef:
            name: rails-config
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql 
        - name: empty-dir
          mountPath: /analytics_app/tmp/sockets
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: empty-dir
        emptyDir: {}                  