apiVersion: v1
kind: Service
metadata:
  namespace: stg
  name: rails
spec:
  selector:
    app: rails
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stg
  name: rails
spec:
  replicas: 1
  revisionHistoryLimit: 3  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: destiny1616/analytics_pjt:v5
        imagePullPolicy: Always
        command:
            - /bin/bash
        args:
            - -c
            - rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0
        envFrom:
        - configMapRef:
            name: rails-config
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          timeoutSeconds: 5
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          timeoutSeconds: 5
          initialDelaySeconds: 10
          periodSeconds: 30        